ExFace/UI5Facade

- Config/exface.UI5Facade.config.json
- Facades/Elements/ServerAdapters/OData2ServerAdapter.php
- Facades/Elements/UI5InputDate.php
- Facades/Elements/UI5InputDateTime.php
- Facades/Elements/UI5InputTime.php
- Facades/js/ui5Custom/dataTypes/MomentDateType.js
- Facades/js/ui5Custom/dataTypes/MomentTimeType.js
server adapter now only adds a date filter to filters if input was parsable to a valid date object
> FIX breaking bug fixed in OData2ServerAdapter, date/time inputs use ICU format

- Facades/Elements/ServerAdapters/OData2ServerAdapter.php
- NEW OData2ServerAdapter supports setting sap-client via url parameter
> FEATURE OData2ServerAdapter supports url parameter for sap-client

- Facades/Elements/UI5NavCrumbs.php
> REFACTOR UI5Breadcrumbs renamed to UI5NavCrumbs

- Config/exface.UI5Facade.config.json
- composer.json
- NEW tinycolor and tinygradient dependency added
> NEW tynicolor and tinygradient dependency added

- Facades/Elements/UI5Panel.php
FIX label of hidden widgets is not shown anymore
FIX breaking error fixed creating multiple elements with same id
> FIX label of hidden widgets is not shown in forms

- Config/exface.UI5Facade.config.json
- Facades/Elements/UI5Chart.php
- NEW echarts library added specifically for heatmap charts
> NEW echarts library added specifically for heatmap charts

- Facades/Elements/Traits/UI5DataElementTrait.php
- Facades/Elements/UI5DataLookupDialog.php
- Facades/Elements/UI5Dialog.php
- using "toString()" led to an error as it did return "=95" instead of "95" for example
- error can be reproduced on the page "nkmnoell.louis.late-vs-on-time" of the nkmnoell louis app using ui5facade
> FIX adding local values using evaluate() instead of toString() function

- Facades/Elements/UI5DataSpreadSheet.php
FIX: filter for dropdown columns need exfTools library, so added it as external modul
> FIX exfTools added as js library to UI5DataSpreadsheet element

- Facades/Elements/UI5Text.php
FIX return empty string in UI5Text element if value is null or undefined
> FIX return empty string in UI5Text element if value is null or undefined

- Facades/Elements/Traits/UI5DataElementTrait.php
- Facades/Elements/UI5MapConfigurator.php
- FIX added trigger 'refresh' event when resetting data for UI5DataElement
- DEV latest fix for resetter in data widgets caused a loop in UI5Map
> FIX added trigger 'refresh' event when resetting data for UI5DataElement

- Facades/Elements/UI5InputForm.php
- Facades/js/survey-js/openui5-survey.css
> NEW Added SurveyJs validation & css classes

- Facades/Elements/UI5Scheduler.php
In e.g. the scheduler for roadmaps the year was displayed incorrectly. For 2024 the scheduler has shown "23" and so on.
> FIX calculation of year

- Facades/Elements/UI5DataSpreadSheet.php
- Facades/js/openui5.template.css
> FIX added 10px offset in spread sheet to enable pull function in bottom right

- Config/exface.UI5Facade.config.json
- Facades/Elements/UI5DiffHtml.php
- Facades/Elements/UI5Value.php
> FIX UI5Value Fixed filter widgets not being properly hidden.

- Facades/js/openui5.facade.js
Average speed values each one second and If a second has no value, than assuming the value from the previous second
> DEV  SemiOffline - average speed  and taking previous speed value for  missing ones

- Facades/js/openui5.facade.js
When the automatic semi-offline feature is disabled and the page is reloaded, it should not automatically turn back on.
> FIX auto_offline_toggle status save for refresh

- Facades/js/openui5.facade.js
When the Automatic Offline mode is turned on or off, scenarios for switching to semi-offline mode are arranged according to the internet speed.
> FIX Auto Offline Toggle-Network Speed Behaviours

- Facades/Elements/UI5DisplayMarkdown.php
- Facades/Elements/UI5InputMarkdown.php
- Facades/Elements/UI5MarkdownDisplay.php
- https://github.com/ExFace/Core/pull/362
> OL-4197 Markdown Textfield fullscreen support

- Facades/Elements/UI5Chart.php
https://github.com/ExFace/Core/pull/358
> DVM964 Expose bar chart filter

- Facades/Elements/UI5Chart.php
- https://github.com/ExFace/Core/pull/370
> DEV UI5Chart minor bugfix and readability improved

- Facades/Elements/Traits/UI5DataElementTrait.php
- Facades/Elements/UI5AbstractElement.php
- Facades/Elements/UI5Dashboard.php
- Facades/Elements/UI5Dialog.php
- Facades/Elements/UI5DynamicPage.php
- Facades/Elements/UI5Gantt.php
- Facades/Elements/UI5Input.php
- Facades/Elements/UI5Scheduler.php
- Facades/Elements/UI5Tab.php
- Facades/Elements/UI5Tabs.php
- Facades/js/openui5.template.css
> FIX Scheduler widget issues

- Facades/Elements/UI5Dialog.php
FIX do not auto-refresh dialogs with changes after actions
> FIX do not auto-refresh dialogs with changes after actions

- Facades/Elements/UI5DataTable.php
this should also fix previous infinite loop issue when re-ordering existing columns
> NEW added optional column support for sap.m.table

- Facades/Elements/UI5InputDateTime.php
If no value is selected, it preselects the given default time.
> feat: added reaction to the default_time property to InputDateTime. 

- Facades/Elements/UI5Display.php
- Facades/Elements/UI5InputCheckBox.php
- Facades/Elements/UI5ObjectStatus.php
- Facades/Elements/UI5ProgressBar.php
- Facades/Formatters/AbstractUI5BindingFormatter.php
- Facades/Formatters/UI5BooleanFormatter.php
- Facades/Formatters/UI5DateFormatter.php
- Facades/Formatters/UI5NumberFormatter.php
- Facades/Formatters/UI5TransparentFormatter.php
- Facades/UI5Facade.php
- Facades/js/ui5Custom/dataTypes/MomentDateType.js
- Depends on https://github.com/ExFace/Core/pull/525
> DEV UI5BindingFormatters updated to support empty_text
